POST http://127.0.0.1:8080/api/v1/school/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJzY2hvb2wtdXNlcnMiLCJmbmFtZSI6Ikl2YW4iLCJsbmFtZSI6Ikl2YW5vdiIsImlzcyI6IlBhcmFnbGlkZXItdmJhYSIsImdyb3VwcyI6WyJURVNUIiwiVVNFUiJdLCJpZCI6IjEyMyIsIm1uYW1lIjoiSS4iLCJleHAiOjIwODI3NTg0MDB9.J96mSPdHbeULAoJN53Sn3iBwfJwcA42MDajfd2bZydY