/**
 * Paragliding schools marketplace
 * App for those who want start learning paragliding or continue. One can find there schools, instructors, trips, all necessary services and equipment for paragliding.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.paraglider.common.kmp.models


/**
 *
 * @param requestId
 * @param debug
 */
open class BaseRequest(
    val requestId: String? = null,
    val debug: Debug? = null
)

