/**
 * Paragliding schools marketplace
 * App for those who want start learning paragliding or continue. One can find there schools, instructors, trips, all necessary services and equipment for paragliding.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.paraglider.common.kmp.models


/**
 *
 * @param mode
 * @param stub
 */

data class Debug(
    val mode: Mode? = null,
    val stub: String? = null
) {

    /**
     *
     * Values: prod,test,stub
     */
    enum class Mode(val value: String) {
        prod("prod"),
        test("test"),
        stub("stub")
    }
}

