/**
* Paragliding schools marketplace
* App for those who want start learning paragliding or continue. One can find there schools, instructors, trips, all necessary services and equipment for paragliding.
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.paraglider.common.kmp.models

/**
 * 
 * @param location город, страна
 * @param photoUrl красивое фото с кэмпа для отображения в карусели
 * @param videoUrl видео прошлого кэмпа, если есть
 * @param shortInfo краткое описание, что где куда
 * @param campDates летные дни кэмпа
 * @param equipmentNeeded включать аренду снаряжения на даты кэмп
 * @param recommendedFlightDates рекомендованные даты поездки
 * @param price стоимость в евро
 */
data class Trip (
    /* город, страна */
    val location: String? = null,
    /* красивое фото с кэмпа для отображения в карусели */
    val photoUrl: String? = null,
    /* видео прошлого кэмпа, если есть */
    val videoUrl: String? = null,
    /* краткое описание, что где куда */
    val shortInfo: String? = null,
    /* летные дни кэмпа */
    val campDates: String? = null,
    /* включать аренду снаряжения на даты кэмп */
    val equipmentNeeded: Boolean? = null,
    /* рекомендованные даты поездки */
    val recommendedFlightDates: String? = null,
    /* стоимость в евро */
    val price: Int? = null
)

